### ISSUE TITLE
Please upgrade to verifier-version 1.236 as default

### ISSUE THREAD

**Issue by YannCebron** [ChrisCarini/intellij-platform-plugin-verifier-action#1]
Thanks a lot for this handy Action!

**Comment by serejke** [comment]
+1, thanks @ChrisCarini!
From now on all important Plugin Verifier's versions will be marked with a GitHub release tag, so that you can keep the Action up-to-date.

**Comment by ChrisCarini** [comment]
Thanks for opening this issue @YannCebron ! (and thank you for the commit mentioning this GH action in the official JB documentation, as well! @hsz just let me know about this - awesome!) and thank you @serejke - this is awesome!

It looks like GH provides the latest release information (including tag) in `https://api.github.com/repos/JetBrains/intellij-plugin-verifier/releases/latest` and I can easily get this in my action via:
```
$ curl -s https://api.github.com/repos/JetBrains/intellij-plugin-verifier/releases/latest | jq .tag_name
"v1.236"
```

Instead of just bumping to `1.236`, I hope you both don't mind if I just look up this version and attempt to use it instead - does that sound reasonable?

I'll have to strip off the `v` that proceeds the number, but that should be totally fine.


Also, would it be possible that when you tag a release, you also include the `.jar` as one of the assets (I believe that doing this will allow me to get the full download URL from the GH endpoint above that I shared) - or, would you rather I continue to have the GH action download the `.jar` file from bintray?

**Comment by serejke** [comment]
@ChrisCarini thank you for the suggestion!
I've added the `verifier-cli-1.236-all.jar` to the release binary distribution. Subsequent releases will also contain the all-in-one jar file, so you can download them automatically bypassing the Bintray :)

**Comment by hsz** [comment]
> Instead of just bumping to 1.236, I hope you both don't mind if I just look up this version and attempt to use it instead - does that sound reasonable?

@ChrisCarini 
It sounds risky since you can't have any tests on your side (tests would increase the Action's work time).

What if there'll be a breaking change + [bus factor](https://en.wikipedia.org/wiki/Bus_factor)?

BTW - I've written [Integration](https://github.com/JetBrains/intellij-plugin-verifier#integration) section in the intellij-plugin-verifier README, and it's already merged.

**Comment by ChrisCarini** [comment]
Hi @hsz - do you mind expanding further what you mean exactly for my own understanding?? :)

You are correct, there are no tests for the GH action (I'd love to add some, but I'm not actually sure how to besides just using the GH action myself), so I want to better understand.

Are you suggesting that if `intellij-plugin-verifier` breaks, this will cause breaking changes in all GH IJ plugins that use this particular action, correct?

Or (and/or), are you suggesting that adding a check to the latest GH release of `intellij-plugin-verifier` increases the possible points of breakage within this GH action itself (ie, the extra call to get this information)?

If so, we could add something to check if the curl request(s) fail (either for getting the information from GH, or getting the jar file from GH), to call back on some sane default(s). Just throwing out some ideas for discussion! :)

Also, thank you for including that on `intellij-plugin-verifier` `README.md`!! 👍 I really appreciate it!!

**Comment by ChrisCarini** [comment]
Hi All,

I just pushed the (very small) change to bump the default version to `1.236`. I did this as this was the explicit ask in this issue (and, I want to try and avoid feature-drift, although I'm excited for more features! See below.)

# But...
Let's continue this discussion! I have a local branch that will allow a default of `LATEST` that will automatically pull from the latest release of `intellij-plugin-verifier` on GitHub and use that version.

Some options I could see:

1. Make `LATEST` the default value, and allow users of the action to specify an explicit version if desired
2. Keep an explicit version of `intellij-plugin-verifier` as the default, but allow users of the action to specify `LATEST` to pull the latest version from GH

## Option 1
**Summary:** Make `LATEST` the default value, and allow users of the action to specify an explicit version if desired
### Pros
- Allows users to not need to modify their GitHub workflows in order to pick up the latest/greatest `intellij-plugin-verifier`
### Cons
- As @hsz [mentioned here](https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action/issues/1#issuecomment-615401043), this could be susceptible to breaking change + bus factor?

## Option 2
**Summary:** Keep an explicit version of `intellij-plugin-verifier` as the default, but allow users of the action to specify `LATEST` to pull the latest version from GH
### Pros
- Would require users specify `LATEST` in order to get the latest/greatest `intellij-plugin-verifier` (could argue this is the case as the user is explicitly asking for the latest in their workflow, and those not are getting something that is stable and 'tested')
### Cons
- Requires users to bump version of action if they want to pick up latest changes


Let me know if I'm missing anything or not thinking of something - and as said, let's continue the discussion; I think this could be a really neat thing to have!

_(As the action creator, I'd love to use `LATEST` so I can stay on top of things - I'd also be equally as happy if I could (1) have this action automatically bump the default to the latest version of `intellij-plugin-verifier` once it's published (either to GH, or Bintray), (2) release a new version of the action to the GitHub marketplace)._

**Comment by hsz** [comment]
I vote for Option 1. TBH, I didn't realize then that there is a possibility to override and freeze the version by the user.

**Comment by ChrisCarini** [comment]
@hsz - cool; I'll proceed with option 1 then - I'll track that under #3 . Thanks again all for the discussion, work and idea here!

**Comment by ChrisCarini** [comment]
@all-contributors

please add @YannCebron for bug, idea, maintenance
please add @serejke for infra, maintenance
please add @hsz for idea, infra, maintenance

**Comment by ChrisCarini** [comment]
@all-contributors

please add @serejke for infra, maintenance.
please add @hsz for idea, infra, maintenance.
