### ISSUE TITLE
How to specify the SNAPSHOT version of an IDE within a specific year?

### ISSUE THREAD

**Issue by takanuva15** [ChrisCarini/intellij-platform-plugin-verifier-action#35]
Hi, I want to verify my plugin using version `2022.1` and whatever the latest snapshot is within `2022.*`. I am confused how to set up my `ide-versions.txt` file to do this?

Right now I have this but the build gives me an error:
```
ideaIC:2022.1
ideaIC:2022-SNAPSHOT
```
(Replacing the 2nd line with `ideaIC:221-SNAPSHOT` also doesn't work either)

Error:
```
Preparing [ideaIC:2022.1]...
  Downloading ideaIC ideaIC:2022.1 from [https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2022.1/ideaIC-2022.1.zip] into [/github/home/ideaIC-2022.1.zip]...
  HTTP/200 - content-type: application/octet-stream
  test of /github/home/ideaIC-2022.1.zip OK
  Extracting [/github/home/ideaIC-2022.1.zip] into [/github/home/ides/ideaIC-2022.1]...
Preparing [ideaIC:221-SNAPSHOT]...
  Downloading ideaIC ideaIC:2022-SNAPSHOT from [https://www.jetbrains.com/intellij-repository/nightly/com/jetbrains/intellij/idea/ideaIC/2022-SNAPSHOT/ideaIC-2022-SNAPSHOT.zip] into [/github/home/ideaIC-2022-SNAPSHOT.zip]...
  curl: (6) Could not resolve host: repo.labs.intellij.net
```

**Comment by ChrisCarini** [comment]
Hi @takanuva15

You'll want to follow the directions in the `README.md` here: https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action#ide-versions - the only change you'll want to make is in step #1 you'll want to look for the version at https://www.jetbrains.com/intellij-repository/snapshots/ (notice the URL is `snapshots` instead of `releases`).

In your case, it looks like you might be interested in trying `221-EAP-SNAPSHOT` (ie, `ideaIC:221-EAP-SNAPSHOT`).

Let me know if that works for you!

**Comment by takanuva15** [comment]
@ChrisCarini  Ah ok thanks, that worked. I didn't realize that the URL was different for snapshots so that probably contributed to my confusion. Might be worthwhile to add a note about the different url for snapshots in the README.
