### ISSUE TITLE
Unzip failing

### ISSUE THREAD

**Issue by filiphr** [ChrisCarini/intellij-platform-plugin-verifier-action#9]
Not sure if I am doing something wrong or there is some other problem.

I am getting 

>Extracting [/github/home/ideaIC-2020.2.zip] into [/github/home/ides/ideaIC-2020.2]...
>unzip: can't read standard input

And the verification fails. The action is [here](https://github.com/mapstruct/mapstruct-idea/runs/1205071834).

**Comment by ChrisCarini** [comment]
Hi @filiphr - Sorry for not responding sooner, I must have missed the notification for this issue! My apologies!

Taking a quick look at this, it appears as though you actually specified `2020.2` two times in the action yaml -> https://github.com/mapstruct/mapstruct-idea/commit/bfa63c9fe1eb8480d2a041c25905bbf687c481e9#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R147

I suspect this is why - you might be thinking: _"hey, it'd be nice if the GH action was smart enough to detect this and just de-dup any duplicates!"_ I'm inclined to agree, but I'm also wondering if it is better that the GH action failed as it points out this duplicate entry (so that it can be removed, granted, a nicer error message would be helpful), or if it'd be better to silently handle this in a logical manner (de-dup, and run once). Let me know your thoughts!

**Comment by filiphr** [comment]
>Taking a quick look at this, it appears as though you actually specified `2020.2` two times in the action yaml

🤦  really silly mistake from me. Thanks for spotting it ant letting me know.

Regarding your other comment, I think that failing and pointing out the duplicate entry is the best course of action. It could be that the user did a typo and didn't notice it. The error will make it easy for the user to spot it. If you de-dup and run once it could mean false sense of security, the user thinking that they have IC-2020.2 and IU-2020.2, but they did typo and they really only have IC-2020.2.

Btw, I removed the duplicated entry and now I have another error:

>Extracting [/github/home/ideaIC-2020.3.zip] into [/github/home/ides/ideaIC-2020.3]...
unzip: short read

I know it is again a mistake on my side that I've added 2020.3 (which is still in EAP mode). Perhaps a better error message here would be nice as well. Saying that there is no such verification check

**Comment by ChrisCarini** [comment]
Hi @filiphr - I just opened PR #13 to address both the duplicate entries, and better zip file handling - please take a look and let me know what you think! I included screenshots on the PR as well so you can see what it will look like.

**Comment by ChrisCarini** [comment]
@all-contributors please add @filiphr for bug
